/**
 * Self-Evolution Protocol Layer (SEPL) — Type System
 *
 * Implements the formal SEPL operator algebra from the Autogenesis paper
 * (arXiv:2604.15034, §4).
 *
 * Core pipeline:  Reflect → Select → Improve → Evaluate → Commit
 * Each operator is a stateful, composable transformation over the
 * evolvable subspace Θ ⊂ RSPL.
 */

import type { ResourceType, ResourceRegistrationRecord } from '../protocol';

// ─── Auxiliary Spaces ────────────────────────────────────────────────────────

/**
 * Trace space Z — structured execution traces from TraceManager.
 * Input to the Reflect operator.
 */
export interface TraceSpace {
  /** Raw execution summary data */
  executionSummary: {
    totalEvents: number;
    errorCount: number;
    failurePatterns: Map<string, number>;
    averageLatencyMs: number;
    toolFailures: Array<{ name: string; errorMessage?: string; count: number }>;
    llmIssues: Array<{ model: string; errorMessage?: string }>;
  };
  /** Session ID this trace covers */
  sessionId?: string;
}

/**
 * Hypothesis space H — causal hypotheses generated by Reflect.
 * Output of Reflect, input to Select.
 */
export interface Hypothesis {
  /** Unique hypothesis ID */
  id: string;
  /** Human-readable description of the root cause */
  description: string;
  /** Confidence score [0, 1] */
  confidence: number;
  /** Which resource types are implicated */
  implicatedTypes: ResourceType[];
  /** Specific resource names suspected */
  suspectedResources: string[];
  /** Suggested fix direction */
  fixDirection: 'prompt_tune' | 'tool_replace' | 'config_change' | 'agent_rewire' | 'memory_update';
  /** Supporting evidence from traces */
  evidence: string[];
}

export interface HypothesisSpace {
  hypotheses: Hypothesis[];
  /** Generation timestamp */
  generatedAt: number;
  /** Reflect operator iteration */
  iteration: number;
}

/**
 * Modification space D — proposed modifications from Select.
 * Output of Select, input to Improve.
 */
export interface Modification {
  /** Modification ID */
  id: string;
  /** Source hypothesis ID */
  hypothesisId: string;
  /** Target resource qualified name "type:name" */
  targetResource: string;
  /** Target resource type */
  resourceType: ResourceType;
  /** What to change */
  changeType: 'variable_update' | 'description_update' | 'metadata_update' | 'template_rewrite';
  /** The proposed new value (opaque until applied) */
  proposedValue: unknown;
  /** Estimated impact score [0, 1] */
  estimatedImpact: number;
  /** Risk level */
  riskLevel: 'low' | 'medium' | 'high';
}

export interface ModificationSpace {
  modifications: Modification[];
  /** Selected hypothesis ID */
  sourceHypothesisId: string;
}

/**
 * Objective specification G — what "better" means.
 * Used by Evaluate to score candidates.
 */
export interface ObjectiveSpec {
  /** Primary metric name (e.g., "success_rate", "latency_p95") */
  primaryMetric: string;
  /** Minimum acceptable value for primary metric */
  minimumThreshold: number;
  /** Secondary metrics to optimize */
  secondaryMetrics?: Array<{ name: string; weight: number }>;
  /** Safety constraints that MUST hold */
  safetyConstraints: Array<{
    name: string;
    check: (state: unknown) => boolean;
  }>;
}

/**
 * Evaluation space S — scores and decisions from Evaluate.
 * Output of Evaluate, input to Commit.
 */
export interface EvaluationResult {
  /** Whether the candidate passed evaluation */
  accepted: boolean;
  /** Primary metric score */
  primaryScore: number;
  /** All metric scores */
  metricScores: Record<string, number>;
  /** Whether all safety constraints passed */
  safetyPassed: boolean;
  /** Which constraints failed (if any) */
  failedConstraints: string[];
  /** Improvement over baseline (positive = better) */
  improvementDelta: number;
  /** Human-readable evaluation summary */
  summary: string;
}

export interface EvaluationSpace {
  results: EvaluationResult[];
  /** Baseline metrics before evolution */
  baseline: Record<string, number>;
  /** Best candidate index (-1 if none accepted) */
  bestCandidateIndex: number;
}

// ─── Evolvable Variable ──────────────────────────────────────────────────────

/**
 * An evolvable variable is a parameter within a resource that SEPL
 * is allowed to modify (g_v = 1 in the trainable subspace Θ).
 */
export interface EvolvableVariable {
  /** Owning resource qualified name "type:name" */
  resourceId: string;
  /** Resource type */
  resourceType: ResourceType;
  /** Variable name within the resource */
  variableName: string;
  /** Whether this variable is learnable (g_v = 1) */
  learnability: 0 | 1;
  /** Current value */
  currentValue: unknown;
  /** Value type hint */
  valueType: 'string' | 'number' | 'boolean' | 'object' | 'template';
  /** Optional bounds */
  bounds?: { min?: number; max?: number };
  /** Optional list of allowed values */
  allowedValues?: unknown[];
}

/**
 * The evolvable state is the collection of all evolvable variables.
 */
export interface EvolvableState {
  /** All variables keyed by "resourceId:variableName" */
  variables: Map<string, EvolvableVariable>;
  /** IDs of trainable variables (g_v = 1) */
  trainableSubset: string[];
}

// ─── SEPL Operator Interface ─────────────────────────────────────────────────

/**
 * A SEPL operator is a composable, stateful transformation.
 *
 * Formal definition: O_i : (S, I) → (S', O)
 * where S is the evolvable state, I is operator-specific input,
 * S' is the updated state, and O is operator-specific output.
 */
export interface SEPLOperator<Input, Output> {
  /** Operator name */
  readonly name: string;
  /** Execute the operator */
  execute(state: EvolvableState, input: Input): Promise<SEPLOutput<Output>>;
}

/**
 * Output of a SEPL operator execution.
 */
export interface SEPLOutput<T> {
  /** Updated evolvable state */
  state: EvolvableState;
  /** Operator-specific output */
  output: T;
  /** Whether the operator succeeded */
  success: boolean;
  /** Error message if failed */
  error?: string;
  /** Execution duration in ms */
  durationMs: number;
}

// ─── Evolution Cycle State ───────────────────────────────────────────────────

/**
 * Complete state of one evolution cycle.
 * Passed through the operator pipeline.
 */
export interface EvolutionCycleState {
  /** Cycle iteration number */
  iteration: number;
  /** Current evolvable state */
  evolvableState: EvolvableState;
  /** Trace input */
  traces: TraceSpace | null;
  /** Generated hypotheses */
  hypotheses: HypothesisSpace | null;
  /** Proposed modifications */
  modifications: ModificationSpace | null;
  /** Evaluation results */
  evaluation: EvaluationSpace | null;
  /** Whether changes were committed */
  committed: boolean;
  /** Cycle start timestamp */
  startedAt: number;
  /** Cycle end timestamp */
  endedAt?: number;
  /** Errors encountered during the cycle */
  errors: string[];
}

/**
 * Result of a complete evolution cycle.
 */
export interface EvolutionCycleResult {
  /** Cycle iteration */
  iteration: number;
  /** Whether any changes were committed */
  committed: boolean;
  /** Committed resource names (if any) */
  committedResources: string[];
  /** Evaluation summary */
  evaluationSummary?: string;
  /** Total cycle duration in ms */
  durationMs: number;
  /** Rollback performed */
  rolledBack: boolean;
}

// ─── Evolution Configuration ─────────────────────────────────────────────────

/**
 * Configuration for the SEPL evolution loop.
 */
export interface SEPLConfig {
  /** Maximum iterations per evolution run */
  maxIterations: number;
  /** Target resource qualified names (empty = all evolvable) */
  targetResources: string[];
  /** Objective specification */
  objective: ObjectiveSpec;
  /** Auto-rollback on evaluation failure */
  autoRollback: boolean;
  /** LLM model for reflection */
  reflectionModel?: string;
  /** Whether to record detailed audit trail */
  auditTrail: boolean;
  /** Timeout per operator (ms) */
  operatorTimeoutMs: number;
}

export const DEFAULT_SEPL_CONFIG: SEPLConfig = {
  maxIterations: 3,
  targetResources: [],
  objective: {
    primaryMetric: 'success_rate',
    minimumThreshold: 0.8,
    safetyConstraints: [],
  },
  autoRollback: true,
  auditTrail: true,
  operatorTimeoutMs: 30000,
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

let hypothesisCounter = 0;
export function generateHypothesisId(): string {
  return `hyp_${Date.now().toString(36)}_${(hypothesisCounter++).toString(36)}`;
}

let modificationCounter = 0;
export function generateModificationId(): string {
  return `mod_${Date.now().toString(36)}_${(modificationCounter++).toString(36)}`;
}

/**
 * Create an empty EvolvableState.
 */
export function createEmptyEvolvableState(): EvolvableState {
  return { variables: new Map(), trainableSubset: [] };
}

/**
 * Build EvolvableState from a set of registered resources.
 */
export function buildEvolvableState(
  records: Array<{ record: ResourceRegistrationRecord; resourceType: ResourceType }>
): EvolvableState {
  const variables = new Map<string, EvolvableVariable>();
  const trainableSubset: string[] = [];

  for (const { record, resourceType } of records) {
    if (record.entity.evolvability !== 1) continue;

    const resourceId = `${resourceType}:${record.entity.name}`;

    // Extract evolvable variables from metadata
    const metadata = record.entity.metadata as Record<string, unknown>;
    for (const [key, value] of Object.entries(metadata)) {
      if (value === undefined || value === null) continue;
      const varKey = `${resourceId}:${key}`;
      const valueType = inferValueType(value);
      const variable: EvolvableVariable = {
        resourceId,
        resourceType,
        variableName: key,
        learnability: 1,
        currentValue: value,
        valueType,
      };
      variables.set(varKey, variable);
      trainableSubset.push(varKey);
    }

    // Description is always evolvable for evolvable resources
    const descKey = `${resourceId}:description`;
    variables.set(descKey, {
      resourceId,
      resourceType,
      variableName: 'description',
      learnability: 1,
      currentValue: record.entity.description,
      valueType: 'string',
    });
    trainableSubset.push(descKey);
  }

  return { variables, trainableSubset };
}

function inferValueType(value: unknown): EvolvableVariable['valueType'] {
  if (typeof value === 'string') {
    // Heuristic: long strings with placeholders are templates
    if (value.length > 100 && (value.includes('{{') || value.includes('${'))) return 'template';
    return 'string';
  }
  if (typeof value === 'number') return 'number';
  if (typeof value === 'boolean') return 'boolean';
  return 'object';
}
